import React, { useEffect, useState } from "react";

const GlobalContext = React.createContext({
    timeBloque: "",
    setTimeBloque: ()=>{},
    anotherDoctor: "",
    setAnotherDoctor: ()=>{},
    statusType: "",
    setStatusType: ()=>{},
    descriptionBloquePatient: "",
    setDescriptionBloquePatient: ()=>{},
    descriptionBloqueDoctor: "",
    setDescriptionBloqueDoctor: ()=>{},
    selectedUser: "",
    setSelectedUser: ()=>{},
    showUserInfo: 1,
    setShowUserInfo: ()=>{},
    descriptionBloque: "",
    setDescriptionBloque: ()=>{},
    monthIndex: 0,
    setMonthIndex: (index) =>{},
    weekIndex: 0,
    setWeekIndex: (index) =>{},
    processState: null, 
    setProcessState: ()=>{},
    eventTrigger: 0,
    setEventTrigger: (index) =>{},
    userId: 0,
    setUserId: (index) =>{},
    userType: "",
    setUserType: (index) =>{},
    smallCalendarMonth: 0,
    setSmallCalendarMonth: (index) =>{},
    daySelected: null,
    setDaySelected: (day) =>{},
    showEventModal: false,
    setShowEventModal: ()=>{},
    dispatchCalEvent: ({type, payload}) => {},
    savedEvents: []
})

export default GlobalContext